'''
Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
'''


def EvenFabonacci(n):
    '''
    return the sum of even fabonacci below n
    args:
        n : int
    ret:
        int
    '''
    sum = 0
    i = 1
    j = 2
    while i < n:
        if i % 2 == 0:
            sum += i
        i, j = j, i + j
    return sum


print(EvenFabonacci(int(input())))
